### ISSUE TITLE
Reportes PDF no renderean gráficas 

### ISSUE THREAD

**Issue by montalvomiguelo** [montalvomiguelo/site-app#34]
Actualmente usamos wickedpdf, tal ves podemos probar con prawn.

Las gráficas las creamos con Google Charts.

**Comment by Chamoy007** [comment]
Si, ya tengo un PDF ejemplo con Prawn en SITE para ver si funcionan las gráficas de Google Charts.

Por eso pregunto a que rama hago el pull request para subirlo en esa.

**Comment by Chamoy007** [comment]
No me deja hacer lo del pull request tratando de crear uno nuevo, solo me deja si selecciono development o master. podrías crear una nueva rama porfa para subirlo en esa. Solo es un pequeño ejemplo para ver si funcionan con ese las grafcas

**Comment by montalvomiguelo** [comment]
Si quieres mándalo a dev amigo ahorita no traigo compu

**Comment by Chamoy007** [comment]
Ya esta =)

**Comment by montalvomiguelo** [comment]
Closes c4086ee975faec3f0524c30f0d406c43d2bfb036
